### ISSUE TITLE
Adding a tex maths formatted output

### ISSUE THREAD

**Issue by janfreyberg** [dgromer/apa#3]
When writing in rmarkdown (to compile to pdf), I prefer my stats reports to be in a tex maths environment. Would it be possible to add this to the package? At the moment, I achieve it with this helper function:

```r
fmt_tex <- function(text){
  return(
    str_replace_all(paste0("$", text, "$"), ', ', '$, $') %>% str_replace_all('petasq', '\\\\eta_p^2'))
)
}
```

This (at the top) compiles better compared to `format='latex'` (middle) and `format='markdown' (bottom):
![image](https://cloud.githubusercontent.com/assets/4092425/26304653/248853d0-3ee4-11e7-93d1-97abfe5166f9.png)

**Comment by dgromer** [comment]
That's what `format = "rmarkdown"` is for (mind the **r**). :)

**Comment by janfreyberg** [comment]
Fair enough - you don't think adding the dollar signs to indicate a maths environment is worthwhile? It prevents linebreaks and IMO generally looks better, and also works as mathjax when going to HTML!

I have a solution for this on a fork, will show you once I have it working properly to see if you think it's worth including.

**Comment by dgromer** [comment]
Preventing line breaks is an important point. What do you mean by "and [...] generally looks better"?

Will take a look.

**Comment by dgromer** [comment]
@janfreyberg could you test `format = latex_math` and give feedback if this is what you meant? (See commit https://github.com/dgromer/apa/commit/30c8c5aa98f7e0153c96adb4adddd5242b781e84)

**Comment by janfreyberg** [comment]
@dgromer that looks exactly like what I thought about. Sorry for not getting back to you sooner - was on holiday until now!

By "generally looks better", I meant that it stays consistent across more formats that you can compile to from Rmarkdown, e.g. it will make inline equations look like other latex equations in the document, and as mentioned looks like maths in HTML output.

Thanks for the implementation!

**Comment by dgromer** [comment]
Thanks for your feedback!
