### ISSUE TITLE
p = 1.0 are displayed as p = .000

### ISSUE THREAD

**Issue by ianhussey** [dgromer/apa#4]
p values seem to be trimmed incorrectly. The output of chisq.test can return p = 1.0. chisq_apa should probably correct this to "p > .99" but instead returns "p = .000", which could lead to incorrect conclusions.

E.g.:
```{r}
df <- data.frame(a <- c(75, 73), b = c(6, 5))
chisq_apa(chisq.test(df))
```

**Comment by dgromer** [comment]
Fixed in fdb3e75, thanks!
