### ISSUE TITLE
Inconsistent Cohen's d for dependent samples

### ISSUE THREAD

**Issue by lcreteig** [dgromer/apa#7]
The output of `cohens_d()` is slightly different when you input the data vs. a call to t.test:

``` r
library(apa)
set.seed(1234)
x <- rnorm(100)
y <- rnorm(100)
cohens_d(x, y, paired = TRUE)
#> [1] -0.1357705
t_obj <- t.test(x, y, paired = TRUE)
cohens_d(t_obj)
#> [1] -0.1350967
```

I believe there's an error in the calculation in the latter case: in line 162 of `cohens_d.R`, `n` is defined as degrees of freedom + 2 (`ttest$parameter + 2`), whereas I think it should be + 1

``` r
unname(t_obj$statistic) / sqrt(unname(t_obj$parameter) + 1)
#> [1] -0.1357705
```

P.S. Thanks for a great package, it's been saving me from a lot of copy-paste/rounding errors otherwise! :+1:

**Comment by dgromer** [comment]
Fixed, thanks!
