### ISSUE TITLE
Error in cohens_d (paired t-test)?

### ISSUE THREAD

**Issue by dfeistauer** [dgromer/apa#8]
Hi,

could it be that in this chunk is an error ?

    if (grepl("Paired", ttest$method)) {
      cohens_d_(t = unname(ttest$statistic), n = unname(ttest$parameter + 
        2), paired = TRUE)
    }

I think an 1 should be added because df = n - 1.
It would be nice if you could check this out.

Thanks.

Daniela

**Comment by dfeistauer** [comment]
I just saw you already corrected it in github.

for other people having the same issue:
library(devtools)
install_github("dgromer/apa")

**Comment by dgromer** [comment]
Replicate of #7.

Should already be in the latest CRAN version. But thanks for reporting anyways!
